error and warning stuff fixed.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -548,7 +548,7 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test -n "$PERL" || { echo "configure: error: "perl not found"" 1>&2; exit 1; }
+test -n "$PERL" || { echo "configure: error: ""perl not found - cannot continue""" 1>&2; exit 1; }
 
 
 # Extract the first word of "uname", so it can be a program name with args.
@@ -580,7 +580,7 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test -n "$UNAME" || { echo "configure: error: "uname not found"" 1>&2; exit 1; }
+test -n "$UNAME" || echo "configure: warning: ""uname not found - cannot build executables""" 1>&2
 
 
 # Extract the first word of "cmp", so it can be a program name with args.
@@ -612,7 +612,7 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test -n "$CMP" || { echo "configure: error: "cmp not found"" 1>&2; exit 1; }
+test -n "$CMP" || echo "configure: warning: ""cmp not found - cannot build executables""" 1>&2
 
 
 for dan_prog in make gmake
@@ -650,11 +650,12 @@ test -n "$MAKE" && break
 done
 test -n "$MAKE" || MAKE=""
 
-test -n "$MAKE" || { echo "configure: error: "make not found"" 1>&2; exit 1; }
+test -n "$MAKE" || echo "configure: warning: ""make not found - cannot continue""" 1>&2
 
+if test -n ${MAKE}; then
 
 echo $ac_n "checking "whether GNU make"""... $ac_c" 1>&6
-echo "configure:658: checking "whether GNU make"" >&5
+echo "configure:659: checking "whether GNU make"" >&5
 ${MAKE} -v -f/dev/null > conf.test 2>&1
 ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/GNU/) {exit 0}; exit 1;}'
 if test ${?} = 1; then
@@ -666,6 +667,7 @@ else
   echo "$ac_t"""yes"" 1>&6
 fi
 
+fi
 
 uname=`${UNAME}`
 OS=UNKNOWN
@@ -676,14 +678,15 @@ test ${uname} = HP-UX && OS=HPUX
 
 echo "$ac_t""""" 1>&6
 echo "checking Fortran compiler" 1>&6
-echo "configure:680: checking Fortran compiler" >&5
+echo "configure:682: checking Fortran compiler" >&5
 
-for dan_prog in f95 f90 frt xlf90
+DEFAULT="N"
+for dan_prog in f95 f90 frt xlf90 g95 g90
 do
 # Extract the first word of "$dan_prog", so it can be a program name with args.
 set dummy $dan_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:687: checking for $ac_word" >&5
+echo "configure:690: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_FC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -713,11 +716,17 @@ test -n "$FC" && break
 done
 test -n "$FC" || FC=""
 
-test -n "$FC" || { echo "configure: error: "Fortran compiler not found"" 1>&2; exit 1; }
+test -n "$FC" || DEFAULT="Y"
 
-${FC} -V > conf.test 2>&1 || ${FC} -v > conf.test 2>&1 || ${FC} -version > conf.test 2>&1
 compiler=UNKNOWN
-
+if test ${DEFAULT} = "Y"; then
+  FC=f95
+  F90SUFFIX=f90
+  echo "configure: warning: "No fortran compiler found!"" 1>&2
+  echo "configure: warning: "Skipping library checks."" 1>&2
+else
+  ${FC} -V > conf.test 2>&1 || ${FC} -v > conf.test 2>&1 || ${FC} -version > conf.test 2>&1
+  
 if test ${compiler} = UNKNOWN; then
   ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/Fujitsu/) {exit 0}; exit 1;}'
   if test ${?} = 0; then
@@ -726,7 +735,7 @@ if test ${compiler} = UNKNOWN; then
 
 fi
 
-
+  
 if test ${compiler} = UNKNOWN; then
   ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/Compaq/) {exit 0}; exit 1;}'
   if test ${?} = 0; then
@@ -735,7 +744,7 @@ if test ${compiler} = UNKNOWN; then
 
 fi
 
-
+  
 if test ${compiler} = UNKNOWN; then
   ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/Digital/) {exit 0}; exit 1;}'
   if test ${?} = 0; then
@@ -744,7 +753,7 @@ if test ${compiler} = UNKNOWN; then
 
 fi
 
-
+  
 if test ${compiler} = UNKNOWN; then
   ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/IBM/) {exit 0}; exit 1;}'
   if test ${?} = 0; then
@@ -753,7 +762,7 @@ if test ${compiler} = UNKNOWN; then
 
 fi
 
-
+  
 if test ${compiler} = UNKNOWN; then
   ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/NAG/) {exit 0}; exit 1;}'
   if test ${?} = 0; then
@@ -762,7 +771,7 @@ if test ${compiler} = UNKNOWN; then
 
 fi
 
-
+  
 if test ${compiler} = UNKNOWN; then
   ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/HP/) {exit 0}; exit 1;}'
   if test ${?} = 0; then
@@ -771,33 +780,13 @@ if test ${compiler} = UNKNOWN; then
 
 fi
 
-rm -f conf.test a.out
-SYSCOMP="${compiler}-${OS}"
+  rm -f conf.test a.out
 
-
-  cat macros | ${PERL} \
-    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *$/!define DEFAULT_NULL/o;' \
-    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *=> *NULL\(\)/#define DEFAULT_NULL       => NULL()/o;' \
-    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *$/!define DEFAULT(X)/o;' \
-    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *= *X/#define DEFAULT(X)         = X/o;' > conf.macros
-  mv -f conf.macros macros
-
-if test ${compiler} = "DEC"; then
-
-  cat macros | ${PERL} \
-    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *$/#define DEFAULT_NULL/o;' \
-    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *=> *NULL\(\)/!define DEFAULT_NULL       => NULL()/o;' \
-    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *$/#define DEFAULT(X)/o;' \
-    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *= *X/!define DEFAULT(X)         = X/o;' > conf.macros
-  mv -f conf.macros macros
-
-fi
-
-havesuffix="0"
-F90SUFFIX=f90
-echo $ac_n "checking "Compiler suffix"""... $ac_c" 1>&6
-echo "configure:800: checking "Compiler suffix"" >&5
-
+    havesuffix="0"
+  F90SUFFIX=f90
+  echo $ac_n "checking "Compiler suffix"""... $ac_c" 1>&6
+echo "configure:789: checking "Compiler suffix"" >&5
+  
 if test ${havesuffix} != "1"; then
 cat > conftest.f90 <<EOF
       program main
@@ -813,7 +802,7 @@ fi
 rm -f conftest.x conftest.f90
 fi
 
-
+  
 if test ${havesuffix} != "1"; then
 cat > conftest.F90 <<EOF
       program main
@@ -829,18 +818,37 @@ fi
 rm -f conftest.x conftest.F90
 fi
 
-echo "$ac_t""${F90SUFFIX}" 1>&6
+  echo "$ac_t""${F90SUFFIX}" 1>&6
 
-echo "$ac_t""""" 1>&6
-echo "checking Libraries" 1>&6
-echo "configure:837: checking Libraries" >&5
-havelibs="0"
-essl="0"
+    
+  cat macros | ${PERL} \
+    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *$/!define DEFAULT_NULL/o;' \
+    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *=> *NULL\(\)/#define DEFAULT_NULL       => NULL()/o;' \
+    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *$/!define DEFAULT(X)/o;' \
+    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *= *X/#define DEFAULT(X)         = X/o;' > conf.macros
+  mv -f conf.macros macros
 
+  if test ${compiler} = "DEC"; then
+  
+  cat macros | ${PERL} \
+    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *$/#define DEFAULT_NULL/o;' \
+    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *=> *NULL\(\)/!define DEFAULT_NULL       => NULL()/o;' \
+    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *$/#define DEFAULT(X)/o;' \
+    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *= *X/!define DEFAULT(X)         = X/o;' > conf.macros
+  mv -f conf.macros macros
+
+  fi
+
+    echo "$ac_t""""" 1>&6
+  echo "checking Libraries" 1>&6
+echo "configure:845: checking Libraries" >&5
+  havelibs="0"
+  essl="0"
+  
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -lcxml"""... $ac_c" 1>&6
-echo "configure:844: checking "for -lcxml"" >&5
+echo "configure:852: checking "for -lcxml"" >&5
 LIBS="-lcxml $LIBS"
 cat > conftest.${F90SUFFIX} <<EOF
       program main
@@ -861,11 +869,11 @@ fi
 rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
-
+  
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -ldxml"""... $ac_c" 1>&6
-echo "configure:869: checking "for -ldxml"" >&5
+echo "configure:877: checking "for -ldxml"" >&5
 LIBS="-ldxml $LIBS"
 cat > conftest.${F90SUFFIX} <<EOF
       program main
@@ -886,11 +894,11 @@ fi
 rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
-
+  
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -lblas -llapack"""... $ac_c" 1>&6
-echo "configure:894: checking "for -lblas -llapack"" >&5
+echo "configure:902: checking "for -lblas -llapack"" >&5
 LIBS="-lblas -llapack $LIBS"
 cat > conftest.${F90SUFFIX} <<EOF
       program main
@@ -911,11 +919,11 @@ fi
 rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
-
+  
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -lblas -lessl"""... $ac_c" 1>&6
-echo "configure:919: checking "for -lblas -lessl"" >&5
+echo "configure:927: checking "for -lblas -lessl"" >&5
 LIBS="-lblas -lessl $LIBS"
 cat > conftest.${F90SUFFIX} <<EOF
       program main
@@ -937,23 +945,27 @@ fi
 rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
-${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/GNU/) {exit 0}; exit 1;}'
-set srcdir = " := .:objects:modules:f90:dependencies:documentation/htmlfiles:scripts:foofiles"
-DEFS=""
-test ${essl} = 1 || DEFS="${DEFS} -DESSL"
+  ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/GNU/) {exit 0}; exit 1;}'
+  set srcdir = " := .:objects:modules:f90:dependencies:documentation/htmlfiles:scripts:foofiles"
+  DEFS=""
+  test ${essl} = 1 || DEFS="${DEFS} -DESSL"
+fi
+SYSCOMP="${compiler}-${OS}"
+
 
 echo "$ac_t""""" 1>&6
 SITECONFIG="${srcdir}/site_config/${SYSCOMP}"
 SITE_CONFIG=${SITECONFIG}
 echo "$ac_t"""Your site_config file is ${SITECONFIG}"" 1>&6
-if test ! -f ${SITECONFIG}; then
-cp -f ${srcdir}/site_config/template ${SITECONFIG}
-tmp="You will need to edit this file, default settings have been used."
-echo "$ac_t""${tmp}" 1>&6
-exit 1
+if test ${compiler} = "UNKNOWN" -o ! -f ${SITECONFIG}; then
+  test -f ${SITECONFIG} || cp -f ${srcdir}/site_config/template ${SITECONFIG}
+  tmp="I do not know the settings for your compiler, using defaults."
+  echo "$ac_t""${tmp}" 1>&6
+  tmp="You will need to edit this file, then rerun configure."
+  echo "$ac_t""${tmp}" 1>&6
 else
-tmp="You may want to edit this file, but it should work as is."
-echo "$ac_t""${tmp}" 1>&6
+  tmp="You may want to edit this file, but it should work as is."
+  echo "$ac_t""${tmp}" 1>&6
 fi
 echo "$ac_t"""See the documentation for more information."" 1>&6
 echo "$ac_t""""" 1>&6
