*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -580,7 +580,7 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test -n "$UNAME" || echo "configure: warning: ""uname not found - cannot build executables""" 1>&2
+test -n "$UNAME" || { echo "configure: error: ""uname not found - cannot continue""" 1>&2; exit 1; }
 
 
 # Extract the first word of "cmp", so it can be a program name with args.
diff --git a/scripts/update_module_file b/scripts/update_module_file
--- a/scripts/update_module_file
+++ b/scripts/update_module_file
@@ -9,8 +9,6 @@
 # directory. In this way, object files which depend on $1 need not
 # be recompiled needlessly!
 #
-# See the "make_dependfile.script" script for a detailed explanation.
-#
 # (c) dylan jayatilaka, university of western australia, 1999
 #
 # $Id$
@@ -22,19 +20,20 @@
 #
 #-------------------------------------------------------------------------
 
-if (! -e new_modules/$1) then
- echo "Error: module file new_modules/$1 does not exist!"
-exit 1
-endif
-if (! -e modules/$1) then
- /bin/mv -f new_modules/$1 modules/$1
- echo "Creating a new $1 file"
-else
- if (`cmp -l new_modules/$1 modules/$1 |& perl -ne 'next if /^    2[567]/; print' | wc -l` == "0") then
-  /bin/rm -f new_modules/$1 
-  echo "Keeping the old $1 file"
+if (-e new_modules/$1) then
+ if (-e modules/$1) then
+  if (`cmp -l new_modules/$1 modules/$1 | perl -ne 'next if /^    2[567]/; print' | wc -l` == "0") then
+   /bin/rm -f new_modules/$1 
+   echo "Keeping the old $1 file"
+  else
+   /bin/mv -f new_modules/$1 modules/$1
+   echo "Updating the old $1 file"
+  endif
  else
   /bin/mv -f new_modules/$1 modules/$1
-  echo "Updating the old $1 file"
+  echo "Creating a new $1 file"
  endif
+else
+ echo "Error: module file new_modules/$1 does not exist\!"
+ exit 1
 endif
