F90SUFFIX now working, initialisation fix for DEC is now a macro.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -515,15 +515,14 @@ fi
 
 
 
-
-
 echo "$ac_t""""" 1>&6
 echo "checking Programs" 1>&6
-echo "configure:523: checking Programs" >&5
+echo "configure:521: checking Programs" >&5
+
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:527: checking for $ac_word" >&5
+echo "configure:526: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -540,7 +539,6 @@ else
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_prog_PERL" && ac_cv_prog_PERL="none"
 fi
 fi
 PERL="$ac_cv_prog_PERL"
@@ -550,7 +548,9 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test ${PERL} = none && { echo "configure: error: "perl not found"" 1>&2; exit 1; }
+test -n "$PERL" || { echo "configure: error: "perl not found"" 1>&2; exit 1; }
+
+
 # Extract the first word of "uname", so it can be a program name with args.
 set dummy uname; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
@@ -571,7 +571,6 @@ else
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_prog_UNAME" && ac_cv_prog_UNAME="none"
 fi
 fi
 UNAME="$ac_cv_prog_UNAME"
@@ -581,11 +580,13 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test ${UNAME} = none && { echo "configure: error: "uname not found"" 1>&2; exit 1; }
+test -n "$UNAME" || { echo "configure: error: "uname not found"" 1>&2; exit 1; }
+
+
 # Extract the first word of "cmp", so it can be a program name with args.
 set dummy cmp; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:589: checking for $ac_word" >&5
+echo "configure:590: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CMP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -602,7 +603,6 @@ else
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_prog_CMP" && ac_cv_prog_CMP="none"
 fi
 fi
 CMP="$ac_cv_prog_CMP"
@@ -612,13 +612,15 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-test ${CMP} = none && { echo "configure: error: "cmp not found"" 1>&2; exit 1; }
-for ac_prog in make gmake
+test -n "$CMP" || { echo "configure: error: "cmp not found"" 1>&2; exit 1; }
+
+
+for dan_prog in make gmake
 do
-# Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+# Extract the first word of "$dan_prog", so it can be a program name with args.
+set dummy $dan_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:622: checking for $ac_word" >&5
+echo "configure:624: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_MAKE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -630,7 +632,7 @@ else
   for ac_dir in $ac_dummy; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_prog_MAKE="$ac_prog"
+      ac_cv_prog_MAKE="$dan_prog"
       break
     fi
   done
@@ -646,11 +648,13 @@ fi
 
 test -n "$MAKE" && break
 done
-test -n "$MAKE" || MAKE="none"
+test -n "$MAKE" || MAKE=""
 
-test ${MAKE} = none && { echo "configure: error: "make not found"" 1>&2; exit 1; }
+test -n "$MAKE" || { echo "configure: error: "make not found"" 1>&2; exit 1; }
+
+
 echo $ac_n "checking "whether GNU make"""... $ac_c" 1>&6
-echo "configure:654: checking "whether GNU make"" >&5
+echo "configure:658: checking "whether GNU make"" >&5
 ${MAKE} -v -f/dev/null > conf.test 2>&1
 ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/GNU/) {exit 0}; exit 1;}'
 if test ${?} = 1; then
@@ -663,7 +667,6 @@ else
 fi
 
 
-
 uname=`${UNAME}`
 OS=UNKNOWN
 test ${uname} = Linux && OS=LINUX
@@ -673,13 +676,14 @@ test ${uname} = HP-UX && OS=HPUX
 
 echo "$ac_t""""" 1>&6
 echo "checking Fortran compiler" 1>&6
-echo "configure:677: checking Fortran compiler" >&5
-for ac_prog in f95 f90 frt xlf90
+echo "configure:680: checking Fortran compiler" >&5
+
+for dan_prog in f95 f90 frt xlf90
 do
-# Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+# Extract the first word of "$dan_prog", so it can be a program name with args.
+set dummy $dan_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:683: checking for $ac_word" >&5
+echo "configure:687: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_FC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -691,7 +695,7 @@ else
   for ac_dir in $ac_dummy; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
-      ac_cv_prog_FC="$ac_prog"
+      ac_cv_prog_FC="$dan_prog"
       break
     fi
   done
@@ -707,9 +711,9 @@ fi
 
 test -n "$FC" && break
 done
-test -n "$FC" || FC="none"
+test -n "$FC" || FC=""
 
-test ${FC} = none && { echo "configure: error: "Fortran compiler not found"" 1>&2; exit 1; }
+test -n "$FC" || { echo "configure: error: "Fortran compiler not found"" 1>&2; exit 1; }
 
 ${FC} -V > conf.test 2>&1 || ${FC} -v > conf.test 2>&1 || ${FC} -version > conf.test 2>&1
 compiler=UNKNOWN
@@ -770,25 +774,82 @@ fi
 rm -f conf.test a.out
 SYSCOMP="${compiler}-${OS}"
 
+
+  cat macros | ${PERL} \
+    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *$/!define DEFAULT_NULL/o;' \
+    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *=> *NULL\(\)/#define DEFAULT_NULL       => NULL()/o;' \
+    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *$/!define DEFAULT(X)/o;' \
+    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *= *X/#define DEFAULT(X)         = X/o;' > conf.macros
+  mv -f conf.macros macros
+
+if test ${compiler} = "DEC"; then
+
+  cat macros | ${PERL} \
+    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *$/#define DEFAULT_NULL/o;' \
+    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *=> *NULL\(\)/!define DEFAULT_NULL       => NULL()/o;' \
+    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *$/#define DEFAULT(X)/o;' \
+    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *= *X/!define DEFAULT(X)         = X/o;' > conf.macros
+  mv -f conf.macros macros
+
+fi
+
+havesuffix="0"
+F90SUFFIX=f90
+echo $ac_n "checking "Compiler suffix"""... $ac_c" 1>&6
+echo "configure:800: checking "Compiler suffix"" >&5
+
+if test ${havesuffix} != "1"; then
+cat > conftest.f90 <<EOF
+      program main
+        write(*,*) 1
+      end
+EOF
+rm -f conftest.x
+csh -c "$FC -O0 -o conftest.x conftest.f90 >& /dev/null"
+if eval "test -e conftest.x"; then
+  havesuffix="1"
+  F90SUFFIX=f90
+fi
+rm -f conftest.x conftest.f90
+fi
+
+
+if test ${havesuffix} != "1"; then
+cat > conftest.F90 <<EOF
+      program main
+        write(*,*) 1
+      end
+EOF
+rm -f conftest.x
+csh -c "$FC -O0 -o conftest.x conftest.F90 >& /dev/null"
+if eval "test -e conftest.x"; then
+  havesuffix="1"
+  F90SUFFIX=F90
+fi
+rm -f conftest.x conftest.F90
+fi
+
+echo "$ac_t""${F90SUFFIX}" 1>&6
+
 echo "$ac_t""""" 1>&6
 echo "checking Libraries" 1>&6
-echo "configure:776: checking Libraries" >&5
+echo "configure:837: checking Libraries" >&5
 havelibs="0"
 essl="0"
 
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -lcxml"""... $ac_c" 1>&6
-echo "configure:783: checking "for -lcxml"" >&5
+echo "configure:844: checking "for -lcxml"" >&5
 LIBS="-lcxml $LIBS"
-cat > conftest.f90 <<EOF
+cat > conftest.${F90SUFFIX} <<EOF
       program main
         write(*,*) lsame("a","b")
         call dgesv(4,nrhs,LU,4,pivot,solution,4,err)
       end
 EOF
 rm -f conftest.x
-csh -c "$FC -O0 $LIBS -o conftest.x conftest.f90 >& /dev/null"
+csh -c "$FC -O0 $LIBS -o conftest.x conftest.${F90SUFFIX} >& /dev/null"
 LIBS="$ac_save_LIBS"
 if eval "test -e conftest.x"; then
   echo "$ac_t""yes" 1>&6
@@ -797,23 +858,23 @@ if eval "test -e conftest.x"; then
 else
   echo "$ac_t""no" 1>&6
 fi
-rm -f conftest.x conftest.f90
+rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
 
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -ldxml"""... $ac_c" 1>&6
-echo "configure:808: checking "for -ldxml"" >&5
+echo "configure:869: checking "for -ldxml"" >&5
 LIBS="-ldxml $LIBS"
-cat > conftest.f90 <<EOF
+cat > conftest.${F90SUFFIX} <<EOF
       program main
         write(*,*) lsame("a","b")
         call dgesv(4,nrhs,LU,4,pivot,solution,4,err)
       end
 EOF
 rm -f conftest.x
-csh -c "$FC -O0 $LIBS -o conftest.x conftest.f90 >& /dev/null"
+csh -c "$FC -O0 $LIBS -o conftest.x conftest.${F90SUFFIX} >& /dev/null"
 LIBS="$ac_save_LIBS"
 if eval "test -e conftest.x"; then
   echo "$ac_t""yes" 1>&6
@@ -822,23 +883,23 @@ if eval "test -e conftest.x"; then
 else
   echo "$ac_t""no" 1>&6
 fi
-rm -f conftest.x conftest.f90
+rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
 
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -lblas -llapack"""... $ac_c" 1>&6
-echo "configure:833: checking "for -lblas -llapack"" >&5
+echo "configure:894: checking "for -lblas -llapack"" >&5
 LIBS="-lblas -llapack $LIBS"
-cat > conftest.f90 <<EOF
+cat > conftest.${F90SUFFIX} <<EOF
       program main
         write(*,*) lsame("a","b")
         call dgesv(4,nrhs,LU,4,pivot,solution,4,err)
       end
 EOF
 rm -f conftest.x
-csh -c "$FC -O0 $LIBS -o conftest.x conftest.f90 >& /dev/null"
+csh -c "$FC -O0 $LIBS -o conftest.x conftest.${F90SUFFIX} >& /dev/null"
 LIBS="$ac_save_LIBS"
 if eval "test -e conftest.x"; then
   echo "$ac_t""yes" 1>&6
@@ -847,23 +908,23 @@ if eval "test -e conftest.x"; then
 else
   echo "$ac_t""no" 1>&6
 fi
-rm -f conftest.x conftest.f90
+rm -f conftest.x conftest.${F90SUFFIX}
 fi
 
 
 if test ${havelibs} != "1"; then
 ac_save_LIBS="$LIBS"
 echo $ac_n "checking "for -lblas -lessl"""... $ac_c" 1>&6
-echo "configure:858: checking "for -lblas -lessl"" >&5
+echo "configure:919: checking "for -lblas -lessl"" >&5
 LIBS="-lblas -lessl $LIBS"
-cat > conftest.f90 <<EOF
+cat > conftest.${F90SUFFIX} <<EOF
       program main
         write(*,*) lsame("a","b")
         call dges(LU,4,4,pivot,solution,0)
       end
 EOF
 rm -f conftest.x
-csh -c "$FC -O0 $LIBS -o conftest.x conftest.f90 >& /dev/null"
+csh -c "$FC -O0 $LIBS -o conftest.x conftest.${F90SUFFIX} >& /dev/null"
 LIBS="$ac_save_LIBS"
 if eval "test -e conftest.x"; then
   echo "$ac_t""yes" 1>&6
@@ -873,35 +934,13 @@ if eval "test -e conftest.x"; then
 else
   echo "$ac_t""no" 1>&6
 fi
-rm -f conftest.x conftest.f90
+rm -f conftest.x conftest.${F90SUFFIX}
 fi
-
 
 ${PERL} -e 'open(A,"conf.test"); while (<A>) {if (/GNU/) {exit 0}; exit 1;}'
-
 set srcdir = " := .:objects:modules:f90:dependencies:documentation/htmlfiles:scripts:foofiles"
 DEFS=""
-if test ${essl} = 1; then
-DEFS="${DEFS} -DESSL"
-fi
-
-
-
-if test ${compiler} = "DEC"; then
-  cat macros | ${PERL} \
-    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *$/#define DEFAULT_NULL/o;' \
-    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *=> *NULL\(\)/!define DEFAULT_NULL       => NULL()/o;' \
-    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *$/#define DEFAULT(X)/o;' \
-    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *= *X/!define DEFAULT(X)         = X/o;' > conf.macros
-  mv -f conf.macros macros
-else
-  cat macros | ${PERL} \
-    -pe '$_ =~ s/^ *# *define *DEFAULT_NULL *$/!define DEFAULT_NULL/o;' \
-    -pe '$_ =~ s/^ *! *define *DEFAULT_NULL *=> *NULL\(\)/#define DEFAULT_NULL       => NULL()/o;' \
-    -pe '$_ =~ s/^ *# *define *DEFAULT\(X\) *$/!define DEFAULT(X)/o;' \
-    -pe '$_ =~ s/^ *! *define *DEFAULT\(X\) *= *X/#define DEFAULT(X)         = X/o;' > conf.macros
-  mv -f conf.macros macros
-fi
+test ${essl} = 1 || DEFS="${DEFS} -DESSL"
 
 echo "$ac_t""""" 1>&6
 SITECONFIG="${srcdir}/site_config/${SYSCOMP}"
@@ -918,6 +957,8 @@ echo "$ac_t""${tmp}" 1>&6
 fi
 echo "$ac_t"""See the documentation for more information."" 1>&6
 echo "$ac_t""""" 1>&6
+
+
 
 
 
@@ -1033,6 +1074,7 @@ s%@MAKE@%$MAKE%g
 s%@FC@%$FC%g
 /@SITECONFIG@/r $SITECONFIG
 s%@SITECONFIG@%%g
+s%@F90SUFFIX@%$F90SUFFIX%g
 s%@SITE_CONFIG@%$SITE_CONFIG%g
 
 CEOF
