much prettier.

diff --git a/scripts/update_module_file b/scripts/update_module_file
--- a/scripts/update_module_file
+++ b/scripts/update_module_file
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+#You can change these two to match your directory structure.
+new_dir=new_modules
+old_dir=modules
+
 #-------------------------------------------------------------------------
 #
 #  >>> Update module file
@@ -16,47 +20,55 @@
 #
 #-------------------------------------------------------------------------
 
-orig_name=$1
 name=$1
+new_mod=new_modules/$name
+old_mod=modules/$name
+
 if [ -z $name ]; then
 echo "Need the module file name as an argument to this script"
 exit 1
 fi
-if [ ! -d new_modules ]; then
-  mkdir new_modules
+if [ ! -d $new_dir ]; then
+ echo "Error: directory $new_dir does not exist!"
+ exit 1
 fi
-if [ ! -d modules ]; then
-  mkdir modules
+if [ ! -d $old_dir ]; then
+ echo "Error: directory $old_dir does not exist!"
+ exit 1
 fi
 
-if [ ! -f new_modules/$name ]; then
+if [ ! -f $new_mod ]; then
    if [ -f $name ]; then
-     /bin/mv $name new_modules
+     /bin/mv $name $new_mod
    else 
       set name = `echo $name:r | tr a-z A-Z`.mod
       if [ -f $name ]; then
-         /bin/mv $name new_modules
+         /bin/mv $name $new_mod
       fi
    fi
 fi
 
-if [ -f new_modules/$name ]; then
- if [ -f modules/$name ]; then
-  if [ -n `cmp new_modules/$name modules/$name` ]; then
-   /bin/rm -f new_modules/$name        # this is for nice compilers
+if [ -f $new_mod ]; then
+ if [ -f $old_mod ]; then
+  if [ -n `cmp $new_mod $old_mod` ]; then
+   /bin/rm -f $new_mod        # for nice compilers
    echo "Keeping the old $name file"
-  elif [ `cmp -l new_modules/$name modules/$name | perl -ne 'next if /^    2[567]/; print' | wc -l` -eq 0 ]; then
-   /bin/rm -f new_modules/$name        # this is for compaq compiler
+  elif [ `cmp -l $new_mod $old_mod | perl -ne 'next if /^    2[567]/; print' | wc -l` -eq 0 ]; then
+   /bin/rm -f $new_mod        # for compaq compiler / tru64
    echo "Keeping the old $name file"
+## this one untested!
+#  elif [ `cmp -l $new_mod $old_mod | perl -ne 'next if /^    (4[89])|(5[01])/; print' | wc -l` -eq 0 ]; then
+#   /bin/rm -f $new_mod        # for compaq compiler / linux
+#   echo "Keeping the old $name file"
   else
-   /bin/mv -f new_modules/$name modules/$name
+   /bin/mv -f $new_mod $old_mod
    echo "Updating the old $name file"
   fi
  else
-  /bin/mv -f new_modules/$name modules/$name
+  /bin/mv -f $new_mod $old_mod
   echo "Creating a new $name file"
  fi
 else
- echo "Error: module file new_modules/$orig_name does not exist!"
+ echo "Error: module file $new_mod does not exist!"
  exit 1
 fi
