*** empty log message ***

diff --git a/trunk/tonto/scripts/update_module_file b/trunk/tonto/scripts/update_module_file
--- a/trunk/tonto/scripts/update_module_file
+++ b/trunk/tonto/scripts/update_module_file
@@ -22,6 +22,10 @@
 #
 #-------------------------------------------------------------------------
 
+if (! -e new_modules/$1) then
+ echo "Error: module file new_modules/$1 does not exist!"
+exit 1
+end
 if (! -e modules/$1) then
  /bin/mv -f new_modules/$1 modules/$1
  echo "Creating a new $1 file"
