Now use Borne shell instead of C shell.

diff --git a/trunk/tonto/scripts/update_module_file b/trunk/tonto/scripts/update_module_file
--- a/trunk/tonto/scripts/update_module_file
+++ b/trunk/tonto/scripts/update_module_file
@@ -1,4 +1,4 @@
-#/bin/csh -f
+#!/bin/sh
 
 #-------------------------------------------------------------------------
 #
@@ -16,37 +16,47 @@
 #
 #-------------------------------------------------------------------------
 
-set orig_name = $1
-set name = $1
+orig_name=$1
+name=$1
+if [ -z $name ]; then
+echo "Need the module file name as an argument to this script"
+exit 1
+fi
+if [ ! -d new_modules ]; then
+  mkdir new_modules
+fi
+if [ ! -d modules ]; then
+  mkdir modules
+fi
 
-if (! -e new_modules/$name) then
-   if (-e $name) then
+if [ ! -e new_modules/$name ]; then
+   if [ -e $name ]; then
      /bin/mv $name new_modules
    else 
       set name = `echo $name:r | tr a-z A-Z`.mod
-      if (-e $name) then
+      if [ -e $name ]; then
          /bin/mv $name new_modules
-      endif
-   endif
-endif
+      fi
+   fi
+fi
 
-if (-e new_modules/$name) then
- if (-e modules/$name) then
-  if ( `cmp -l new_modules/$name modules/$name` == 0 ) then
+if [ -e new_modules/$name ]; then
+ if [ -e modules/$name ]; then
+  if `cmp new_modules/$name modules/$name` ; then
    /bin/rm -f new_modules/$name        # this is for nice compilers
    echo "Keeping the old $name file"
-  else if (`cmp -l new_modules/$name modules/$name | perl -ne 'next if /^    2[567]/; print' | wc -l` == "0") then
+  elif [ `cmp -l new_modules/$name modules/$name | perl -ne 'next if /^    2[567]/; print' | wc -l` -eq 0 ]; then
    /bin/rm -f new_modules/$name        # this is for compaq compiler
    echo "Keeping the old $name file"
   else
    /bin/mv -f new_modules/$name modules/$name
    echo "Updating the old $name file"
-  endif
+  fi
  else
   /bin/mv -f new_modules/$name modules/$name
   echo "Creating a new $name file"
- endif
+ fi
 else
- echo "Error: module file new_modules/$orig_name does not exist\!"
+ echo "Error: module file new_modules/$orig_name does not exist!"
  exit 1
-endif
+fi
